name: Сборка и тестирование

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3

    - name: Установка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make

    - name: Сборка проекта
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Тестирование проекта
      run: |
        cd build
        ./CPP/Lb_1.4 --help